drop table if exists member CASCADE;
create table member
(
    id bigint generated by default as identity,
          name varchar(255),
          primary key (id)

);
-- cmd 관리자 권한 실행, h2 -> din -> .\h2.bat으로 h2.bat실행